config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'diaries#index'
  resources :diaries do
    resources :comments, only: :create
    resources :favorites, only:[:create, :destroy]
  end
  resources :users do
    get :favorites, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: 'ご飯・離乳食' },
    { id: 2, name: 'おもちゃ遊び' },
    { id: 3, name: '保育園' },
    { id: 4, name: 'お昼寝' },
    { id: 5, name: '絵本・音楽・ゲーム' },
    { id: 6, name: 'グッズ' },
    { id: 7, name: 'スポーツ・レジャー' },
    { id: 8, name: '病気' },
    { id: 9, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :diaries
end

app/models/children_age.rb
class ChildrenAge < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '0~5才' },
    { id: 2, name: '6~12才' },
    { id: 3, name: '12~15才' },
    { id: 4, name: '0~12才' },
    { id: 5, name: '0~15才' },
    { id: 6, name: '6~15才' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/children_number.rb
class ChildrenNumber < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '1' },
    { id: 2, name: '2' },
    { id: 3, name: '3' },
    { id: 4, name: '4' },
    { id: 5, name: '5' },
    { id: 6, name: '6' },
    { id: 7, name: '7' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/children_sex.rb
class ChildrenSex < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '男の子のみ' },
    { id: 2, name: '男の子と女の子' },
    { id: 3, name: '女の子のみ' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :diary

  validates :content, presence: true
end

app/models/diary.rb
class Diary < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  has_one_attached :image
  belongs_to :user, optional: true
  has_many :comments
  has_many :favorites, dependent: :destroy
  with_options presence: true do
    validates :title, :text, :image
  end

  with_options numericality: { other_than: 0, message: "can't be blank" } do
    validates :category_id
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :diary
  validates_uniqueness_of :diary_id, scope: :user_id
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sex
  belongs_to :children_sex
  belongs_to :children_number
  belongs_to :children_age
  has_many   :diaries
  has_many   :comments
  has_many :favorites, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'

    validates :nickname, :birthday
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/,
                                     message: 'is invalid. Input full-width characters' }

    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/,
                                    message: 'is invalid. Input full-width characters' }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/,
                                          message: 'is invalid. Input full-width katakana characters' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/,
                                         message: 'is invalid. Input full-width katakana characters' }
  end

  with_options numericality: { other_than: 0, message: "can't be blank" } do
    validates :sex_id, :children_sex_id, :children_number_id, :children_age_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[nickname last_name first_name last_name_kana first_name_kana
                                               birthday sex_id children_number_id children_sex_id children_age_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, diary_id: params[:diary_id])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_diary, only: %i[show edit update destroy]
  before_action :move_to_index, only: %i[edit update destroy]
  def index
    @diaries = Diary.order('created_at DESC')
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @diary.comments.includes(:user)
  end

  def edit; end

  def update
    if @diary.update(diary_params)
      redirect_to diary_path
    else
      render :edit
    end
  end

  def destroy
    @diary.destroy
    redirect_to root_path
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :text, :category_id, :image).merge(user_id: current_user.id)
  end

  def set_diary
    @diary = Diary.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @diary.user_id
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_diary
  before_action :authenticate_user!   # ログイン中のユーザーのみに許可（未ログインなら、ログイン画面へ移動）

  # お気に入り登録
  def create
    return unless @diary.user_id != current_user.id # 投稿者本人以外に限定

    @favorite = Favorite.create(user_id: current_user.id, diary_id: @diary.id)
    redirect_back(fallback_location: root_path)
  end

  # お気に入り削除
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, diary_id: @diary.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def set_diary
    @diary = Diary.find(params[:diary_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @diaries = user.diaries
    
    favorites = Favorite.where(user_id: current_user.id).pluck(:diary_id)  # ログイン中のユーザーのお気に入りのdiary_idカラムを取得
    @favorite_list = Diary.find(favorites)     # diariesテーブルから、お気に入り登録済みのレコードを取得
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_diary.html.erb
<div class="diary-explain-box">
 <%= link_to diary_path(diary.id)  do %>
    <table class="detail-table">
   
      <tbody>
        <tr>
          <th class="detail-diary">タイトル</th>
          <td class="detail-value"><%= diary.title %></td>
        </tr>
        <tr>
          <th class="detail-diary">ニックネーム</th>
          <td class="detail-value"><%=(diary.user).nickname  %></td>
        </tr>
        <tr>
          <th class="detail-diary">カテゴリー</th>
          <td class="detail-value"><%= "#{Category.find(diary.category_id).name}" %></td>
        </tr>
        <tr>
          <th class="detail-diary">日記画像</th>
          <td class="detail-value"><%= image_tag diary.image , class: "diary-img"  %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
  </div>


  <%= link_to('/diaries/new', class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>日記を投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

app/views/diaries/edit.html.erb
<%#app/assets/stylesheets/diaries/new.css %>

<div class="diaries-contents">
  <header class="diaries-header">
    <%= link_to image_tag('kodomo-logo.png' , size: '185x50'), "/" %>

  </header>
  <div class="diaries-main">
    <h2 class="diaries-title">日記投稿内容を入力</h2>
    <%= form_with model: @diary,local: true do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>
    

    <%# 日記画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        日記関連画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"diary-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-diaries">
      <div class="weight-bold-text">
        日記タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"diaries-text", id:"diary-name", placeholder:"日記タイトル", maxlength:"40" %>
      <div class="diaries-explain">
       <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"diary-category"}) %>
        <div class="weight-bold-text">
          日記内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"diaries-text", id:"diary-info", placeholder:"日記の詳細内容を入力してください。。"  ,maxlength:"3000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 下部ボタン %>
    <div class="write-btn-contents">
      <%= f.submit "投稿する" ,class:"write-btn" %>
      <%=link_to 'もどる', diary_path(@diary.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="diaries-footer">
   
    <%= link_to image_tag('kodomo-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Kodomo,Inc.
    </p>
  </footer>
</div>

app/views/diaries/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  
  <div class='title-contents'>
    <h2 class='service-title'>
      子育てに関する悩み、喜びを共有するアプリ
    </h2>
    <p class='service-explain'>
      KODOMOは子育てに関する悩みを皆で共有、
    </p>
    <p class='service-explain'>
      情報交換ができるアプリです
    </p>
    
  </div>
  

  

  <%# 画面中央の「会員数日本一位」帯部分 %>

  <div class='ad-contents'>
    <h2 class='ad-title'>
      KODOMOの使い方
    </h2>
    <div class= 'ad-image'>
    <p class='ad-explain'>
      うちの子は○歳だけど、まだこれができていないけど大丈夫なのか？
    </p>
    <p class='ad-explain'>
      今日お買い物に言ったらうちの子が店員さんに笑顔でバイバイ、可愛いと言ってもらえた！
    </p>
    <p class='ad-explain'>
      等々日々の育児に関する悩みや日常の喜びを発信し、同じ悩みを持っている、同じ経験があるお父さん、お母さんが情報交換や交流を行い、育児のストレスや悩みの解消するためのコミュニケーションツールです。
    </p>
    
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

<%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      KODOMOの主要機能
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "kodomo-intro01.jpg", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>日記</span>
          投稿機能
        </h3>
        <p class='reason-list-description'>
          子育てに関する悩みや情報を日記形式で投稿
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kodomo-intro02.jpg", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>コメント</span>
          機能
        </h3>
        <p class='reason-list-description'>
          悩みに対する共感やアドバイス、グッズに対する質問などができる
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kodomo-intro03.jpg", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>お気に入り</span>
          登録機能
        </h3>
        <p class='reason-list-description'>
          共感できるユーザーや有用な情報のある投稿、ユーザーを登録できる
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>


  <%# 日記投稿一覧 %>
  <div class='diary-contents'>
    <h2 class='title'>最近の投稿</h2>
  
    <ul class='diary-lists'>

      <% @diaries.each do |diary| %>
      <li class='list'>
        <%= link_to diary_path(diary.id)  do %>
        <div class='diary-img-content'>
         
          
            <%= image_tag diary.image, class: "diary-img" if diary.image.attached? %>
         

        </div>
        <div class='diary-info'>
          <h3 class='diary-name'>
            <%= "#{diary.title}" %>
          </h3>
          <div class='diary-name'>
            <span><%= "#{(diary.user).nickname}" %></span>
            </div>
          
          <div class='diary-category'>
            <span><%= "#{Category.find(diary.category_id).name}" %></span>
          
          </div>
      
         <% end %>
        <% end %>
      </li>

      <%# 日記のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにする %>
       <% if @diaries.blank? then %>
      <li class='list'>
        <%= link_to "#" do %>
        <div class='item-img-content'>
          <%= image_tag "diary-sample.jpg", class: "diary-img" %>
        </div>
        <div class='diary-info'>
          <h3 class='diary-title'>
            <%= "日記タイトル" %>
          </h3>
          <div class='diary-user'>
            <span>投稿者：<%= "投稿者名" %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
     
      <%# //日記のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにする %>

      <%# 日記投稿がない場合は以下のダミー投稿が表示されるようにする %>
      <%# 投稿がある場合は表示されないようにする %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "kodomo-sample2.jpg", class: "diary-img" %>
        <div class='item-info'>
          <h3 class='diary-title'>
            おじいちゃんとおでかけ
          </h3>
          <div class='diary-user'>
            <span>投稿者：まったりおばさん</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "diary-sample3.jpg", class: "diary-img" %>
        <div class='item-info'>
          <h3 class='diary-title'>
            初めての注射
          </h3>
          <div class='diary-user'>
            <span>投稿者：駆け出しママ</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
       <% end %>
      <%# //投稿がある場合は表示されないようにする %>
      <%# //日記投稿がない場合は以下のダミー投稿が表示されるようにしましょう %>
    </ul>
  </div>
  <%# /日記投稿一覧 %>
</div>
 <%= link_to('/diaries/new', class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>日記を投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

<%= render "shared/footer" %>

app/views/diaries/new.html.erb
<div class="diaries-contents">
  <header class="diaries-header">
    <%= link_to image_tag('kodomo-logo.png' , size: '185x50'), "/" %>

  </header>
  <div class="diaries-main">
    <h2 class="diaries-title">日記投稿内容を入力</h2>
    <%= form_with model: @diary,local: true do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>
    

    <%# 日記画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        日記関連画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"diary-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-diaries">
      <div class="weight-bold-text">
        日記タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"diaries-text", id:"diary-name", placeholder:"日記タイトル", maxlength:"40" %>
      <div class="diaries-explain">
       <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"diary-category"}) %>
        <div class="weight-bold-text">
          日記内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"diaries-text", id:"diary-info", placeholder:"日記の詳細内容を入力してください。。"  ,maxlength:"3000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 下部ボタン %>
    <div class="write-btn-contents">
      <%= f.submit "投稿する" ,class:"write-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="diaries-footer">
   
    <%= link_to image_tag('kodomo-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Kodomo,Inc.
    </p>
  </footer>
</div>

app/views/diaries/show.html.erb
<%= render "shared/header" %>

<%# 日記の概要 %>
<div class="diary-show">
  <div class="diary-box">
    <h2 class="title">
      <%= "#{@diary.title}" %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @diary.image ,class:"diary-box-img" %>
    </div>
    
    <%# ログインしているユーザーと投稿しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
    <%if user_signed_in? && current_user.id == @diary.user_id %>
    <%= link_to "日記の編集", edit_diary_path(@diary.id), method: :get, class: "diary-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", diary_path(@diary.id), method: :delete, class:"diary-destroy" %>
    <% end %>




    <%# //ログインしているユーザーと投稿しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="diary-explain-box">
      <span><%= @diary.title %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-diary">タイトル</th>
          <td class="detail-value"><%= @diary.title %></td>
        </tr>
        <tr>
          <th class="detail-diary">ニックネーム</th>
          <td class="detail-value"><%=(@diary.user).nickname  %></td>
        </tr>
        <tr>
          <th class="detail-diary">カテゴリー</th>
          <td class="detail-value"><%= "#{Category.find(@diary.category_id).name}" %></td>
        </tr>
        <tr>
          <th class="detail-diary">日記内容</th>
          <td class="detail-value"><%= @diary.text %></td>
        </tr>
      </tbody>
    </table>
   <div class="option">
    <%unless user_signed_in? && current_user.id == @diary.user_id then%>

    <div class='star-btn' id="favorite_<%= @diary.id %>">
     <%= render "favorites/favorite", diary: @diary %>
     <%else%>
     <div class="favorite-btn">
       <p><span>お気に入りされた数: </span><%= @diary.favorites.count %></p>
     </div>
    </div>
    <% end %>
   </div>
  </div>
  <div class="comment-box">
   <%unless user_signed_in? && current_user.id == @diary.user_id then%>
      <%= form_with(model: [@diary, @comment], local: true) do |form| %>
     <%= form.text_area :content, class:"comment-text",placeholder:"コメントする"%>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
     <%= form.submit "コメントする" %>
     <% end %>
    <% end %>    
  </div>
  <div class="container">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.content %>
        </p>
      <% end %>
   </div>
  <%# /日記の概要 %>


  
</div>


<%= render "shared/footer" %>

app/views/favorites/_favorite.html.erb
<% if user_signed_in?  %>
   <div class="option" >
   <%= link_to diary_favorites_path(@diary.id), method: :post do %>
     <div class="favorite-btn">
       <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
       <p><span>お気に入り登録: </span><br><%=  "登録数 = #{@diary.favorites.count}"%></p>
     </div>
    <% end %>
    <%= link_to diary_favorite_path(@diary.id), method: :delete do %>
     <div class="report-btn">
       <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
       <p>お気に入り解除 </p>
     </div>
    <% end %>
     
     <% else %>
       <p>※※※お気に入りをするにはユーザー登録をしましょう※※※</p>
     <% end %>
   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kodomo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    子育ての悩みをみんなで共有する日記投稿アプリ
  </p>
  <h2 class='ad-footer-title'>
    どんな些細なことでも投稿してください
  </h2>
 
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='kodomo-details'>
      <h2 class='footer-content-head'>KODOMO</h2>
      
    </div>
    
   
  </div>
  <%#= link_to image_tag("a", class:"logo-white"), "#" %>
  <p>© KODOMO</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("kodomo-logo.png", class:"kodomo-icon"), "/" %>
   
   <div>
    <ul class='nav' >
    
      <% if user_signed_in?%>
      <li><%= link_to "#{current_user.nickname}さんのマイページ",  "/users/#{current_user.id}", class: "user-nickname" %></li> 
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, method: :delete, class: "logout" %></li> 
       <% else %>
      <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    
    </ul>
   </div>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>

  <%= image_tag "kodomo-logo.png", class:"second-fotter-logo"%>
  
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("kodomo-logo.png", class:"second-logo"), "/" %>
</header>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="mypage-contents">
  <p><%= @nickname %>さんの投稿一覧</p>

  <% @diaries.each do |diary| %>
    <%= render partial: "diaries/diary", locals: { diary: diary } %>
  <% end %>
 <div class='diary-contents'>
    <h2 class='title'>お気に入り一覧</h2>
  <% if @favorite_list.present?%>
    <ul class='diary-lists'>

       <% @favorite_list.each do |diary|%>
      <li class='list'>
        <%= link_to diary_path(diary.id)  do %>
        <div class='diary-img-content'>
         
          
            <%= image_tag diary.image, class: "diary-img" if diary.image.attached? %>
         

        </div>
        <div class='diary-info'>
          <h3 class='diary-name'>
            <%= "#{diary.title}" %>
          </h3>
          <div class='diary-name'>
            <span><%= "#{(diary.user).nickname}" %></span>
            </div>
          
          <div class='diary-category'>
            <span><%= "#{Category.find(diary.category_id).name}" %></span>
          
          </div>
      
         <% end %>
        <% end %>
        <% end %>
      </li>
   </ul>
</div>